name: Webshop UI Tests
on:
   push:
      branches: [main, master]
   pull_request:
      branches: [main, master]
jobs:
   test:
      timeout-minutes: 60
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - uses: actions/setup-node@v3
           with:
              node-version: 18
         - name: Install dependencies
           run: npm ci
         - name: Install Playwright Browsers
           run: npx playwright install --with-deps
         - name: Display directory
           run: ls -l
         - name: Run tests
           run: npm run test:github
         - uses: actions/upload-artifact@v3
           if: always()
           with:
              name: cucumber_report.html
              path: report/
              retention-days: 30
